DELIMITER //
USE check;

CREATE EVENT delete_when_full
	ON SCHEDULE EVERY 1 HOUR STARTS '2019-10-24 18:30:00'
	DO
	BEGIN IF (SELECT COUNT(*) FROM log) > 90 THEN
		DELETE FROM log ORDER BY id DESC limit 5;
	END IF;
END //
